feat: update eventemitter for react native 0.65
AgoraIO-Extensions/react-native-agora pull request #414
Opened 2021-09-22 19:15 UTC by radko93

This fixes event emitter cleanup on React Native 0.65. It's backward compatible. I think `removeListener` should be hidden or deprecated but I leave that up to you.
 
fixes #412

2021-11-05 04:29 UTC, zhangtao1104 approved these changes

2021-11-05 06:12 UTC, LichKing-2234 requested changes

2021-11-05 06:12 UTC, LichKing-2234 commented on src/common/RtcChannel.native.ts
> +    map.get(listener);
Pls remove this line

2021-11-05 06:12 UTC, LichKing-2234 commented on src/common/RtcEngine.native.ts
> +    map.get(listener);
Pls remove this line

2021-11-29 08:39 UTC, radko93 commented
@LichKing-2234 I updated with develop and removed the lines you wanted. But I have not tested if removing this is OK.

2021-11-30 05:51 UTC, LichKing-2234 approved these changes

2021-11-30 05:51 UTC, merged